global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "express"
    static_configs:
      - targets: ["express:3000"]

  - job_name: "express-photos"
    static_configs:
      - targets: ["express-photos:3002"]

  - job_name: "mongodb-exporter"
    static_configs:
      - targets: ["mongodb-exporter:4004"]


