name: Node.js CI

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: ./week1

      - name: Install dependencies
        run: npm install
        working-directory: ./week1


      - name: Run tests
        run: npm test
        working-directory: ./week1


      - name: Check coverage threshold
        run: |
          coverage=$(cat ./week1/coverage/coverage-summary.json | jq '.total.lines.pct')
          threshold=20 
          if (( $(echo "$coverage < $threshold" | bc -l) )); then
            echo "Error: Test coverage is below threshold ($coverage%)"
            exit 1
          fi

